### ISSUE TITLE
ERROR on indented expressions that aren't really indented

### ISSUE THREAD

**Issue by KaranAhlawat** [tree-sitter/tree-sitter-scala#433] opened 2024-10-19 14:49 UTC
### Commit of tree-sitter-scala you tested this on

v0.23.2

### A code sample showing the error

```scala
def hi =
    e match
    case 1 => "Ok"
    case _ => "Also Ok"
```

### Show the error node

```
(function_definition name: def (identifier) body: =
 (indented_cases
  (ERROR (identifier) match)
  (case_clause case pattern: (integer_literal) body: => (string))
  (case_clause case
   pattern: (wildcard _)
   body: => (string))))
```

### What do you expect the tree to look like

```
(function_definition name: def (identifier) body: =
 (indented_block
  (match_expression value: (identifier) match
   body: 
    (indented_cases
     (case_clause case pattern: (integer_literal) body: => (string))
     (case_clause case
      pattern: (wildcard _)
      body: => (string))))))
```

### Where are you experiencing this error?

Emacs

**Comment by KaranAhlawat** [comment] 2024-10-19 14:51
Not really sure if this is an error or expected behavior, since technically the cases *aren't* indented in relation to the match expression, but this is valid Scala code

**Comment by eed3si9n** [comment] 2024-10-19 16:06
Thanks for the report! If it's a valid Scala code, then it's tree-sitter-scala's bug.

**Comment by SethTisue** [comment] 2024-10-23 17:48
I kind of hate that it's valid Scala code, but it is.

**Comment by susliko** [comment] 2024-11-21 07:30
Looks like a duplicate of https://github.com/tree-sitter/tree-sitter-scala/issues/264

**Closed** 2024-11-21 07:42 UTC
